### ISSUE TITLE
helm upgrade 시 deployment rollout이 안 된다

### ISSUE THREAD

**Issue by Zeniuus** [Stair-Crusher-Club/scc-server#124]
https://helm.sh/ko/docs/howto/charts_tips_and_tricks/#%EC%9E%90%EB%8F%99-%EB%94%94%ED%94%8C%EB%A1%9C%EC%9D%B4%EB%A8%BC%ED%8A%B8-%EC%A0%84%ED%99%98roll <- 이거 따라 했는데 왜 안 되징

**Comment by bellatoris** [comment]
please check it https://github.com/Stair-Crusher-Club/scc-server/pull/116#discussion_r1027248295

**Comment by Zeniuus** [comment]
일단 수동으로 restart 처리함
